# Declaring Variables and Tensors


## Declaring Tensors



Tensors are the primary data structure that TensorFlow uses to operate on the computational
graph. We can declare these tensors as variables and or feed them in as placeholders. First
we must know how to create tensors.



## How to do it…

 ### Here we will cover the main ways to create tensors in TensorFlow:

In [192]:
import tensorflow as tf
import numpy as np

# Create a zero filled tensor


In [193]:
zero = tf.zeros([4 , 4] )

In [194]:
with tf.Session() as f:
    z = f.run(zero)
    print(z)
    

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


###  create a one filled tensor 

In [195]:
one  = tf.ones([5 ,5] )

with tf.Session() as sess:
      o = sess.run(one)
      print(o)


[[ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]


### Create a constat filled 



 


In [196]:
ff = tf.fill([2,2],2.4 )



with tf.Session() as sess:
      o = sess.run(ff)
      print(o)


[[ 2.4000001  2.4000001]
 [ 2.4000001  2.4000001]]


### crea a tensor out of an existing constant 

In [197]:
cons = tf.constant([2 ,3 ,2 ])

In [198]:

with tf.Session() as sess:
      o = sess.run(cons)
      print(o)

[2 3 2]


###  linsapce 

In [199]:
lispace_ = tf.linspace(0.0 , 5 , 5)
range_ = tf.range(0 , 8  ,delta=2)


In [200]:
with tf.Session() as sess:
      o = sess.run(lispace_)
      print(o)

[ 0.    1.25  2.5   3.75  5.  ]


In [201]:
with tf.Session() as sess:
      o = sess.run(range_)
      print(o)

[0 2 4 6]


### The following generated random numbers are from a uniform distribution:

In [202]:
r = tf.random_uniform((2 , 2),minval=0 , maxval=1 )

In [203]:
with tf.Session() as sess:
    a = sess.run(r)
    print(a)

[[ 0.33011007  0.49642408]
 [ 0.27576208  0.95690501]]


### To get a tensor with random draws from a normal distribution, as follows:

In [204]:
nor = tf.random_normal([2 ,2 ] ,mean = 0.0 ,  stddev = 6 )

In [205]:
with tf.Session() as sess:
    a = sess.run(nor)
    print(a)

[[  8.44168186  -5.44399357]
 [ -1.48789549 -14.46354961]]


## tf.truncated_normal

In [206]:
truc = tf.truncated_normal([3,3], mean = 0 , stddev = 0.1 )


with tf.Session() as sess:
    a = sess.run(truc)
    print(a)

[[-0.13349013 -0.02135821  0.0263113 ]
 [-0.0199069  -0.07731593  0.09586126]
 [-0.15395992 -0.01636971  0.06939714]]


### using the Variable() function

In [212]:
m = tf.Variable(tf.zeros([2,3]))

In [214]:
"""with tf.Session() as sess:
    res = sess.run(m)
    print(res)
    
"""

'with tf.Session() as sess:\n    res = sess.run(m)\n    print(res)\n    \n'

### placeholder in the feed dictionary

In [218]:
import tensorflow as tf
import numpy as np 


sess = tf.Session()

x = tf.placeholder(tf.float32 ,[2,2])
y =tf.identity(x)

x_vals = np.random.rand(2,2)
sess.run(y , feed_dict= {x:x_vals})


array([[ 0.89769572,  0.03154356],
       [ 0.19663724,  0.12536174]], dtype=float32)

In [ ]:
#pag 28